<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <AssemblyVersion>2.0.0.2</AssemblyVersion>
	  <ApplicationIcon>icones\logo-app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icones\configuracao-de-dados-windows-metro-16.png" />
    <None Remove="icones\icons8-adicionar-a-coleção-40.png" />
    <None Remove="icones\icons8-adicionar-a-coleção-80.png" />
    <None Remove="icones\icons8-adicionar-propriedade-40.png" />
    <None Remove="icones\icons8-adicionar-propriedade-80.png" />
    <None Remove="icones\icons8-copiar-40.png" />
    <None Remove="icones\icons8-copiar-80.png" />
    <None Remove="icones\icons8-detalhes-40.png" />
    <None Remove="icones\icons8-detalhes-80.png" />
    <None Remove="icones\icons8-editar-propriedade-40.png" />
    <None Remove="icones\icons8-editar-propriedade-80.png" />
    <None Remove="icones\icons8-excluir-40.png" />
    <None Remove="icones\icons8-excluir-80.png" />
    <None Remove="icones\icons8-impressão-40.png" />
    <None Remove="icones\icons8-impressão-80.png" />
    <None Remove="icones\icons8-lista-de-verificação-40.png" />
    <None Remove="icones\icons8-lista-de-verificação-80.png" />
    <None Remove="icones\icons8-ms-excel-blue-ui-120.png" />
    <None Remove="icones\icons8-ms-excel-blue-ui-16.png" />
    <None Remove="icones\icons8-ms-excel-blue-ui-32.png" />
    <None Remove="icones\icons8-ms-excel-blue-ui-96.png" />
    <None Remove="icones\icons8-next-page-blue-ui-16.png" />
    <None Remove="icones\icons8-next-page-blue-ui-32.png" />
    <None Remove="icones\icons8-next-page-blue-ui-96.png" />
    <None Remove="icones\icons8-pesquisar-40.png" />
    <None Remove="icones\icons8-pesquisar-80.png" />
    <None Remove="icones\icons8-salvar-40.png" />
    <None Remove="icones\icons8-salvar-80.png" />
    <None Remove="icones\icons8-salvar-como-blue-ui-16.png" />
    <None Remove="icones\icons8-salvar-como-blue-ui-32.png" />
    <None Remove="icones\icons8-salvar-como-blue-ui-96.png" />
    <None Remove="icones\icons8-usu_0025c3_0025a1rio-de-g_0025c3_0025aanero-neutro-windows-metro-16.png" />
    <None Remove="icones\icons8-vassoura-40.png" />
    <None Remove="icones\icons8-vassoura-80.png" />
    <None Remove="icones\logo-app.ico" />
    <None Remove="icones\logo.png" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="ClosedXML" Version="0.105.0" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="Dapper" Version="2.1.79" />
	  <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
	  <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
	  <PackageReference Include="Mapster" Version="10.0.7" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
      <PackageReference Include="Syncfusion.Presentation.Wpf" Version="27.1.58" />
      <PackageReference Include="Syncfusion.UI.WPF.NET" Version="27.1.58" />
      <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.8" />
	  <PackageReference Include="Telerik.UI.for.Wpf.80.Xaml" Version="2025.2.521" />
	  <PackageReference Include="Xceed.Words.NET" Version="5.2.26166.7850" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="icones\icons8-adicionar-propriedade-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="icones\icons8-adicionar-propriedade-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modelos\BASE.pptx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="imagem_1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modelos\MODELO-PADRAO.pptx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modelos\MODELO_PROJ_COM.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Impressos\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BibliotecasSIG\BibliotecasSIG\BibliotecasSIG.csproj" />
    <ProjectReference Include="..\..\Update\Update.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icones\configuracao-de-dados-windows-metro-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-adicionar-a-coleção-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-adicionar-a-coleção-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-copiar-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-copiar-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-detalhes-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-detalhes-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-editar-propriedade-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-editar-propriedade-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-excluir-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-excluir-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-impressão-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-impressão-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-lista-de-verificação-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-lista-de-verificação-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-ms-excel-blue-ui-120.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-ms-excel-blue-ui-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-ms-excel-blue-ui-32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-ms-excel-blue-ui-96.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-next-page-blue-ui-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-next-page-blue-ui-32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-next-page-blue-ui-96.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-pesquisar-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-pesquisar-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-salvar-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-salvar-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-salvar-como-blue-ui-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-salvar-como-blue-ui-32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-salvar-como-blue-ui-96.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-usu_0025c3_0025a1rio-de-g_0025c3_0025aanero-neutro-windows-metro-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-vassoura-40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\icons8-vassoura-80.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\logo-app.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icones\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\GridViewResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GridViewResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\GridViewResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>GridViewResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

	<Target Name="IncludeEmptyFolders" AfterTargets="Publish">
		<MakeDir Directories="$(PublishDir)Impressos" />
	</Target>

</Project>
